### ISSUE TITLE
Fire interrupts out of the class

### ISSUE THREAD

**Issue by joaoc** [andysworkshop/stm32plus#85] opened 2015-01-15 23:56 UTC
Hi,

This is more a doubt than a issue, but i don't know where to put it...
 
I'm trying to write a program using interrupts, but i don´t want to stay stuck inside the class where i defined it.

I manage to replicate this issue using the Timer_interrupt example.

I'v tried to create a global pointer and initialization on the main, but with the same result.

It's possible to do what i want?

```c++
 * Timer demonstration: This demo uses the advanced control timer Timer1 to do something
 * not very advanced at all. We set the timer to count up and down, basically it oscillates
 * between 0 and 5000 at 1Khz. Each time one of the limits is hit the system raises an
 * 'Update' interrupt. We handle this interrupt by toggling a LED on PF6. The net result
 * of this is that the LED flashes on and off for a second in each of those states.
 *
 * If you are running this on the STM32F4DISCOVERY board then you can replace all reference
 * to PF6 with PD13 to use the onboard LED on that board.
 *
 * If you are running this on the VL or F0 DISCOVERY boards then you can replace all reference
 * to PF6 with PC8 to use the onboard LED on that board.
 *
 * Compatible MCU:
 *   STM32F0
 *   STM32F1
 *   STM32F4
 *
 * Tested on devices:
 *   STM32F051R8T6
 *   STM32F100RBT6
 *   STM32F103ZET6
 *   STM32F407VGT6
 */

class TimerInterruptsTest  {

  protected:

    enum { LED_PIN = 5 };

    /*
     * We'll need these as member variables so that we can see them from the interrupt handler
     */

    GpioA<DefaultDigitalOutputFeature<LED_PIN> > _pa;
    bool _ledState;

  public:

    void run() {

      /*
       * Initialise timer1 running from the high speed internal APB2 (APB on the F0)
       * clock with an interrupt feature
       */

      Timer1<
        Timer1InternalClockFeature,       // the timer clock source is APB2 (APB on the F0)
        Timer1InterruptFeature            // gain access to interrupt functionality
      > timer;

      /*
       * We've got a LED on PF[6] and it's active LOW. Set it up here and switch it off.
       */

      _pa[LED_PIN].set();
      _ledState=false;

      /*
       * Set ourselves up as an observer for interrupts raised by the timer class.
       */

      timer.TimerInterruptEventSender.insertSubscriber(
          TimerInterruptEventSourceSlot::bind(this,&TimerInterruptsTest::onInterrupt)
        );


      /*
       * Set an up-down-timer up to tick at 5000Hz with an auto-reload value of 4999
       * The timer will count from 0 to 4999 inclusive, raise an Update interrupt and
       * then go backwards back down to 0 where it'll raise another Update interrupt
       * and start again. Each journey from one end to the other takes 1 second.
       *
       * Note that the lowest frequency you can set is 1098 for a 72Mhz timer clock source.
       * This is because the maximum prescaler value is 65536 (72Mhz/65536 = 1098Hz).
       */

      timer.setTimeBaseByFrequency(5000,4999,TIM_CounterMode_CenterAligned3);

      /*
       * Enable just the Update interrupt, clearing any spurious pending flag first
       */

      timer.clearPendingInterruptsFlag(TIM_IT_Update);
      timer.enableInterrupts(TIM_IT_Update);

      /*
       * Start the timer
       */

      timer.enablePeripheral();

      /*
       * It's all running automatically now
       */

      //for(;;);  //here it works
    }

    /*
     * Observer callback function. This is called when the update interrupt that we've
     * enabled is fired.
     */

    void onInterrupt(TimerEventType tet,uint8_t /* timerNumber */) {

      if(tet==TimerEventType::EVENT_UPDATE) {

        /*
         * Toggle the LED state.
         */

        _ledState^=true;
        _pa[LED_PIN].setState(_ledState);
      }
    }
};


/*
 * Main entry point
 */

int main() {

  // we're using interrupts, initialise NVIC

  Nvic::initialise();

  TimerInterruptsTest test;
  test.run();

  for(;;); //if i do the wait here it doesn't work.


  // not reached
  return 0;
}
```

**Comment by andysworkshop** [comment] 2015-01-16 19:26
The problem is simply that the instance of the `timer` variable is local to the `run()` method and will go out of scope and be destructed when that method completes. To fix, move this...

     Timer1<
        Timer1InternalClockFeature,       // the timer clock source is APB2 (APB on the F0)
        Timer1InterruptFeature            // gain access to interrupt functionality
      > timer;

...declaration to a class member variable. Be aware that the constructors in the timer hierarchy will initialise the peripheral so you might need to be careful where you declare the instance of the class so that the initialisation happens in the correct order relative to the rest of what your program is doing. That may not matter to you but I thought I'd point it out..

**Closed** 2015-02-11 20:47 UTC
Labels: question
